apiVersion: v1
kind: Service
metadata:
  name: "adamcool-{{  .Chart.Name }}-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http  
    port: {{ .Values.service.servicePort }}
  selector:
    app: "{{  .Chart.Name }}-selector"
